import { Order } from '@/types/order';
import { Product } from '@/types/product';
import { UserProfile } from '@/types/profile';
import { User } from '@/types/user';
import { CommunityPost, CommunityCategory } from '@/types/community';
import { Review, TopReviewer } from '@/types/review';

const MOCK_ORDERS: Order[] = [
  {
    id: 'ORDER-001',
    userId: '1',
    items: [
      {
        id: 'cart-1',
        productId: '1',
        name: '나스티 망고 아이스',
        brand: '나스티',
        price: 12000,
        image: '/images/nasty-mango.jpg',
        quantity: 2,
      },
      {
        id: 'cart-2',
        productId: '3',
        name: '맥스웰 블루베리 타르트',
        brand: '맥스웰',
        price: 13500,
        image: '/images/maxwell-blueberry.jpg',
        quantity: 1,
      },
    ],
    totalAmount: 37500,
    status: 'delivered',
    orderDate: '2024-08-15',
    deliveryDate: '2024-08-18',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
  {
    id: 'ORDER-002',
    userId: '1',
    items: [
      {
        id: 'cart-3',
        productId: '2',
        name: '코스모스 스트로베리 밀크',
        brand: '코스모스',
        price: 8000,
        image: '/images/cosmos-strawberry.jpg',
        quantity: 3,
      },
    ],
    totalAmount: 24000,
    status: 'shipped',
    orderDate: '2024-08-28',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
  {
    id: 'ORDER-003',
    userId: '1',
    items: [
      {
        id: 'cart-4',
        productId: '5',
        name: '나스티 그린애플',
        brand: '나스티',
        price: 11000,
        image: '/images/nasty-greenapple.jpg',
        quantity: 1,
      },
    ],
    totalAmount: 11000,
    status: 'processing',
    orderDate: '2024-09-01',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
];

const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: '나스티 망고 아이스',
    brand: '나스티',
    price: 12000,
    originalPrice: 15000,
    discount: 20,
    rating: 4.8,
    reviewCount: 124,
    image: '/images/nasty-mango.jpg',
    images: [
      '/images/nasty-mango.jpg',
      '/images/nasty-mango-2.jpg',
      '/images/nasty-mango-3.jpg',
    ],
    description:
      '망고의 달콤함과 시원한 아이스가 만나 완벽한 조화를 이루는 프리미엄 액상',
    flavor: '망고 아이스',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  {
    id: '2',
    name: '코스모스 스트로베리 밀크',
    brand: '코스모스',
    price: 8000,
    rating: 4.6,
    reviewCount: 89,
    image: '/images/cosmos-strawberry.jpg',
    images: [
      '/images/cosmos-strawberry.jpg',
      '/images/cosmos-strawberry-2.jpg',
    ],
    description: '신선한 딸기와 부드러운 우유의 완벽한 조화',
    flavor: '스트로베리 밀크',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  {
    id: '3',
    name: '맥스웰 블루베리 타르트',
    brand: '맥스웰',
    price: 13500,
    originalPrice: 16000,
    discount: 15,
    rating: 4.7,
    reviewCount: 156,
    image: '/images/maxwell-blueberry.jpg',
    images: [
      '/images/maxwell-blueberry.jpg',
      '/images/maxwell-blueberry-2.jpg',
      '/images/maxwell-blueberry-3.jpg',
    ],
    description: '진짜 블루베리 타르트를 먹는 듯한 달콤하고 새콤한 맛',
    flavor: '블루베리 타르트',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  {
    id: '4',
    name: '더원 바닐라 크림',
    brand: '더원',
    price: 9500,
    rating: 4.4,
    reviewCount: 67,
    image: '/images/theone-vanilla.jpg',
    images: ['/images/theone-vanilla.jpg', '/images/theone-vanilla-2.jpg'],
    description: '부드럽고 진한 바닐라 크림의 깊은 맛',
    flavor: '바닐라 크림',
    nicotine: '6mg',
    volume: '30ml',
    inStock: false,
    isPopular: false,
    isNew: false,
  },
  {
    id: '5',
    name: '나스티 그린애플',
    brand: '나스티',
    price: 11000,
    rating: 4.5,
    reviewCount: 78,
    image: '/images/nasty-greenapple.jpg',
    images: ['/images/nasty-greenapple.jpg'],
    description: '상큼한 그린애플의 깔끔하고 시원한 맛',
    flavor: '그린애플',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
];

const MOCK_USER_PROFILES: UserProfile[] = [
  {
    id: '1',
    name: '김민준',
    email: 'test@juicepick.com',
    phone: '010-1234-5678',
    birthDate: '1990-05-15',
    gender: 'male',
    address: {
      zipCode: '06142',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
    },
    preferences: {
      newsletter: true,
      smsMarketing: false,
      pushNotifications: true,
    },
  },
  {
    id: '2',
    name: '관리자',
    email: 'admin@juicepick.com',
    phone: '010-9876-5432',
    birthDate: '1985-03-20',
    gender: 'male',
    address: {
      zipCode: '04512',
      address: '서울특별시 중구 세종대로 110',
      detailAddress: '관리자실',
    },
    preferences: {
      newsletter: true,
      smsMarketing: true,
      pushNotifications: true,
    },
  },
  {
    id: '3',
    name: '일반 사용자',
    email: 'user@example.com',
    phone: '010-5555-6666',
    birthDate: '1995-12-10',
    gender: 'female',
    address: {
      zipCode: '07654',
      address: '경기도 성남시 분당구 판교역로 166',
      detailAddress: '101동 2002호',
    },
    preferences: {
      newsletter: false,
      smsMarketing: false,
      pushNotifications: false,
    },
  },
];

const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'test@juicepick.com',
    password: '123456',
    name: '테스트 유저',
    role: 'user',
  },
  {
    id: '2',
    email: 'admin@juicepick.com',
    password: 'admin123',
    name: '관리자',
    role: 'admin',
  },
  {
    id: '3',
    email: 'user@example.com',
    password: 'password',
    name: '일반 사용자',
    role: 'user',
  },
];

const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 1,
    title: '나스티 쿠션맨 맛 후기 - 완전 대박!',
    content:
      '드디어 나스티 쿠션맨 액상을 써봤는데 정말 맛이 좋네요. 과일 맛이 진짜 진하고 목넘김도 부드러워서 계속 빨게 되더라고요. 니코틴 3mg로 했는데 딱 적당한 것 같아요.',
    author: '베이프러버',
    category: '제품후기',
    likes: 42,
    views: 1234,
    comments: 18,
    createdAt: '2시간 전',
    isPinned: true,
    isHot: true,
  },
  {
    id: 2,
    title: '액상 DIY 레시피 공유합니다',
    content:
      '오랫동안 연구한 DIY 레시피를 공유해요. PG/VG 비율은 30/70으로 하고 니코틴은 6mg으로 맞춰봤는데 정말 만족스러운 결과가 나왔어요. 재료와 비율을 자세히 알려드릴게요.',
    author: 'DIY마스터',
    category: 'DIY/팁',
    likes: 28,
    views: 856,
    comments: 12,
    createdAt: '4시간 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 3,
    title: '초보자 질문 - 니코틴 함량 추천 부탁드려요',
    content:
      '담배를 끊으려고 전자담배를 시작하려는데 니코틴 함량을 얼마나 해야할지 모르겠어요. 하루에 한 갑 정도 피웠는데 몇 mg로 시작하는게 좋을까요? 경험자분들 조언 부탁드립니다.',
    author: '금연도전자',
    category: '질문/답변',
    likes: 15,
    views: 623,
    comments: 25,
    createdAt: '6시간 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 4,
    title: '온라인 쇼핑몰별 가격 비교해봤어요',
    content:
      '주요 온라인몰에서 같은 제품 가격을 비교해봤는데 차이가 꽤 나네요. 쿠폰이나 적립금까지 고려하면 더 차이가 벌어져요. 정리한 내용 공유드릴게요.',
    author: '가격헌터',
    category: '정보공유',
    likes: 67,
    views: 2341,
    comments: 8,
    createdAt: '8시간 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 5,
    title: '맥스웰 신제품 출시 소식!',
    content:
      '맥스웰에서 새로운 맛 출시한다고 하네요. 망고 키위 믹스라고 하는데 언제부터 판매하는지 아시는 분 계신가요? 벌써 기대되네요.',
    author: '뉴스헌터',
    category: '뉴스/소식',
    likes: 23,
    views: 789,
    comments: 14,
    createdAt: '12시간 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 6,
    title: '코일 수명 늘리는 꿀팁 공유',
    content:
      '코일을 오래 쓸 수 있는 방법들을 정리해봤습니다. 프라이밍 방법부터 사용 중 주의사항까지 상세히 설명드릴게요. 도움이 되시길 바랍니다.',
    author: '베테랑유저',
    category: 'DIY/팁',
    likes: 31,
    views: 1456,
    comments: 6,
    createdAt: '1일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 7,
    title: '전자담배 시작한 지 6개월 후기',
    content:
      '금연을 위해 전자담배를 시작한 지 6개월이 되었네요. 처음엔 어색했는데 이제는 완전히 적응했고 담배 생각도 안 나요. 과정과 팁을 공유해드릴게요.',
    author: '금연성공자',
    category: '제품후기',
    likes: 89,
    views: 3421,
    comments: 31,
    createdAt: '2일 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 8,
    title: '액상 보관 방법 질문이요',
    content:
      '액상을 어떻게 보관해야 오래 쓸 수 있나요? 냉장고에 넣어도 되는지, 직사광선만 피하면 되는지 궁금해요.',
    author: '보관고민',
    category: '질문/답변',
    likes: 12,
    views: 445,
    comments: 8,
    createdAt: '3일 전',
    isPinned: false,
    isHot: false,
  },
];

const MOCK_COMMUNITY_CATEGORIES: CommunityCategory[] = [
  { name: '전체', count: 1247, color: 'bg-blue-50 text-blue-700' },
  { name: '제품후기', count: 456, color: 'bg-green-50 text-green-700' },
  { name: '질문/답변', count: 321, color: 'bg-orange-50 text-orange-700' },
  { name: 'DIY/팁', count: 234, color: 'bg-purple-50 text-purple-700' },
  { name: '정보공유', count: 156, color: 'bg-red-50 text-red-700' },
  { name: '뉴스/소식', count: 80, color: 'bg-indigo-50 text-indigo-700' },
];

const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    productName: '나스티 쿠션맨 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '정말 맛있는 액상입니다!',
    content:
      '처음에는 기대 안했는데 정말 맛있어요. 과일 맛이 진하고 목넘김도 부드러워서 매일 사용하고 있습니다. 특히 아침에 커피 대신 이걸로 시작하면 기분이 좋아져요.',
    author: '베이프러버123',
    date: '2024-01-15',
    helpful: 42,
    notHelpful: 3,
    comments: 8,
    verified: true,
    pros: ['진한 과일맛', '부드러운 목넘김', '가성비 좋음'],
    cons: ['냄새가 좀 강함'],
    tags: ['과일맛', '입문자추천', '가성비'],
  },
  {
    id: 2,
    productName: '코스모스 블루베리 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '블루베리 맛이 진짜네요',
    content:
      '블루베리 액상을 많이 써봤는데 이게 제일 진짜 블루베리 같아요. 달콤함도 적당하고 연무량도 만족스럽습니다. 다만 가격이 조금 비싼게 아쉬워요.',
    author: '과일맛헌터',
    date: '2024-01-14',
    helpful: 28,
    notHelpful: 2,
    comments: 5,
    verified: true,
    pros: ['진짜 블루베리맛', '적당한 단맛', '좋은 연무량'],
    cons: ['가격이 비쌈', '용량이 아쉬움'],
    tags: ['블루베리', '진짜맛', '연무량'],
  },
  {
    id: 3,
    productName: '맥스웰 민트 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '민트맛은 좋은데...',
    content:
      '민트 향이 정말 시원하고 좋아요. 여름에 쓰기 딱 좋을 것 같습니다. 하지만 코일 수명이 짧아지는 느낌이에요. 그래도 민트 좋아하시면 추천드려요.',
    author: '민트매니아',
    date: '2024-01-13',
    helpful: 19,
    notHelpful: 1,
    comments: 12,
    verified: false,
    pros: ['시원한 민트', '여름용으로 좋음'],
    cons: ['코일 수명 단축', '목이 아플 때 있음'],
    tags: ['민트', '시원함', '여름용'],
  },
  {
    id: 4,
    productName: '더원 망고 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '망고 맛 진짜 끝내줍니다',
    content:
      '망고 액상 중에서 최고인 것 같아요. 향도 좋고 맛도 진짜 망고 같아요. 니코틴도 적당해서 하루 종일 써도 목이 아프지 않아요. 강력 추천!',
    author: '망고사랑',
    date: '2024-01-12',
    helpful: 35,
    notHelpful: 0,
    comments: 6,
    verified: true,
    pros: ['진짜 망고맛', '좋은 향', '적당한 니코틴'],
    cons: [],
    tags: ['망고', '향좋음', '니코틴적당'],
  },
  {
    id: 5,
    productName: '베이프윌 딸기 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '딸기 맛 괜찮아요',
    content:
      '달달한 딸기 맛이 좋네요. 인공적인 맛이 아니라 자연스러운 딸기 맛입니다. 가격도 저렴해서 부담 없이 쓸 수 있어요.',
    author: '딸기좋아',
    date: '2024-01-11',
    helpful: 22,
    notHelpful: 4,
    comments: 3,
    verified: true,
    pros: ['자연스러운 딸기맛', '저렴한 가격', '달달함'],
    cons: ['연무량이 적음'],
    tags: ['딸기', '저렴', '달콤'],
  },
  {
    id: 6,
    productName: '나스티 그린애플 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '상큼한 그린애플!',
    content:
      '정말 상큼한 그린애플 맛이에요. 새콤달콤해서 질리지 않고 계속 빨게 되네요. 특히 더운 날씨에 시원하게 즐기기 좋아요.',
    author: '애플러버',
    date: '2024-01-10',
    helpful: 31,
    notHelpful: 2,
    comments: 9,
    verified: true,
    pros: ['상큼한 맛', '질리지 않음', '시원함'],
    cons: ['조금 시큼함'],
    tags: ['사과', '상큼', '시원함'],
  },
  {
    id: 7,
    productName: '코스모스 스트로베리 밀크',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '딸기우유 그 자체!',
    content:
      '진짜 딸기우유 마시는 느낌이에요. 달콤하고 부드러워서 스트레스 받을 때 피우면 기분이 좋아져요. 연무량도 많고 만족스럽습니다.',
    author: '스트로베리킹',
    date: '2024-01-09',
    helpful: 45,
    notHelpful: 1,
    comments: 11,
    verified: true,
    pros: ['진짜 딸기우유맛', '달콤함', '좋은 연무량'],
    cons: ['칼로리 걱정됨'],
    tags: ['딸기', '우유', '달콤', '연무량'],
  },
  {
    id: 8,
    productName: '더원 바닐라 크림',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '바닐라 맛은 좋지만...',
    content:
      '바닐라 크림 맛은 정말 좋아요. 부드럽고 달콤해서 디저트 같은 느낌입니다. 하지만 너무 달아서 금방 질려요. 가끔씩 즐기기에는 좋을 것 같아요.',
    author: '바닐라매니아',
    date: '2024-01-08',
    helpful: 18,
    notHelpful: 5,
    comments: 4,
    verified: false,
    pros: ['부드러운 바닐라', '디저트 같은 맛'],
    cons: ['너무 달음', '쉽게 질림'],
    tags: ['바닐라', '디저트', '달콤'],
  },
];

const MOCK_TOP_REVIEWERS: TopReviewer[] = [
  { name: '베이프러버123', reviews: 156, helpful: 2341 },
  { name: '과일맛헌터', reviews: 89, helpful: 1567 },
  { name: '리뷰왕', reviews: 134, helpful: 1432 },
  { name: '액상마스터', reviews: 67, helpful: 987 },
];

const FILTER_TAGS = [
  '전체',
  '과일맛',
  '민트',
  '담배맛',
  '디저트',
  '입문자추천',
  '가성비',
  '프리미엄',
  '고농도',
  '저농도',
];

export {
  MOCK_ORDERS,
  MOCK_PRODUCTS,
  MOCK_USER_PROFILES,
  MOCK_USERS,
  MOCK_COMMUNITY_POSTS,
  MOCK_COMMUNITY_CATEGORIES,
  MOCK_REVIEWS,
  MOCK_TOP_REVIEWERS,
  FILTER_TAGS,
};
