import { Order } from '@/types/order';
import { Product } from '@/types/product';
import { UserProfile } from '@/types/profile';
import { User } from '@/types/user';
import { CommunityPost, CommunityCategory } from '@/types/community';
import { Review, TopReviewer } from '@/types/review';

const MOCK_ORDERS: Order[] = [
  {
    id: 'ORDER-001',
    userId: '1',
    items: [
      {
        id: 'cart-1',
        productId: '1',
        name: '나스티 망고 아이스',
        brand: '나스티',
        price: 12000,
        image: '/images/nasty-mango.jpg',
        quantity: 2,
      },
      {
        id: 'cart-2',
        productId: '3',
        name: '맥스웰 블루베리 타르트',
        brand: '맥스웰',
        price: 13500,
        image: '/images/maxwell-blueberry.jpg',
        quantity: 1,
      },
    ],
    totalAmount: 37500,
    status: 'delivered',
    orderDate: '2024-08-15',
    deliveryDate: '2024-08-18',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
  {
    id: 'ORDER-002',
    userId: '1',
    items: [
      {
        id: 'cart-3',
        productId: '2',
        name: '코스모스 스트로베리 밀크',
        brand: '코스모스',
        price: 8000,
        image: '/images/cosmos-strawberry.jpg',
        quantity: 3,
      },
    ],
    totalAmount: 24000,
    status: 'shipped',
    orderDate: '2024-08-28',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
  {
    id: 'ORDER-003',
    userId: '1',
    items: [
      {
        id: 'cart-4',
        productId: '5',
        name: '나스티 그린애플',
        brand: '나스티',
        price: 11000,
        image: '/images/nasty-greenapple.jpg',
        quantity: 1,
      },
    ],
    totalAmount: 11000,
    status: 'processing',
    orderDate: '2024-09-01',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
];

const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: '나스티 망고 아이스',
    brand: '나스티',
    price: 12000,
    originalPrice: 15000,
    discount: 20,
    rating: 4.8,
    reviewCount: 124,
    image: '/images/nasty-mango.jpg',
    images: [
      '/images/nasty-mango.jpg',
      '/images/nasty-mango-2.jpg',
      '/images/nasty-mango-3.jpg',
    ],
    description:
      '망고의 달콤함과 시원한 아이스가 만나 완벽한 조화를 이루는 프리미엄 액상',
    flavor: '망고 아이스',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  {
    id: '2',
    name: '코스모스 스트로베리 밀크',
    brand: '코스모스',
    price: 8000,
    rating: 4.6,
    reviewCount: 89,
    image: '/images/cosmos-strawberry.jpg',
    images: [
      '/images/cosmos-strawberry.jpg',
      '/images/cosmos-strawberry-2.jpg',
    ],
    description: '신선한 딸기와 부드러운 우유의 완벽한 조화',
    flavor: '스트로베리 밀크',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  {
    id: '3',
    name: '맥스웰 블루베리 타르트',
    brand: '맥스웰',
    price: 13500,
    originalPrice: 16000,
    discount: 15,
    rating: 4.7,
    reviewCount: 156,
    image: '/images/maxwell-blueberry.jpg',
    images: [
      '/images/maxwell-blueberry.jpg',
      '/images/maxwell-blueberry-2.jpg',
      '/images/maxwell-blueberry-3.jpg',
    ],
    description: '진짜 블루베리 타르트를 먹는 듯한 달콤하고 새콤한 맛',
    flavor: '블루베리 타르트',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  {
    id: '4',
    name: '더원 바닐라 크림',
    brand: '더원',
    price: 9500,
    rating: 4.4,
    reviewCount: 67,
    image: '/images/theone-vanilla.jpg',
    images: ['/images/theone-vanilla.jpg', '/images/theone-vanilla-2.jpg'],
    description: '부드럽고 진한 바닐라 크림의 깊은 맛',
    flavor: '바닐라 크림',
    nicotine: '6mg',
    volume: '30ml',
    inStock: false,
    isPopular: false,
    isNew: false,
  },
  {
    id: '5',
    name: '나스티 그린애플',
    brand: '나스티',
    price: 11000,
    rating: 4.5,
    reviewCount: 78,
    image: '/images/nasty-greenapple.jpg',
    images: ['/images/nasty-greenapple.jpg'],
    description: '상큼한 그린애플의 깔끔하고 시원한 맛',
    flavor: '그린애플',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  // ID: 6
  {
    id: '6',
    name: '프리미엄 레몬허브',
    brand: '프리미엄',
    price: 14500,
    originalPrice: 17000,
    discount: 15,
    rating: 4.6,
    reviewCount: 92,
    image: '/images/premium-lemonherb.jpg',
    images: [
      '/images/premium-lemonherb.jpg',
      '/images/premium-lemonherb-2.jpg',
    ],
    description: '상큼한 레몬과 허브의 자연스러운 조화',
    flavor: '레몬허브',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  // ID: 7
  {
    id: '7',
    name: '나스티 쿨민트',
    brand: '나스티',
    price: 10500,
    rating: 4.3,
    reviewCount: 134,
    image: '/images/nasty-coolmint.jpg',
    images: ['/images/nasty-coolmint.jpg'],
    description: '시원하고 상쾌한 민트의 극강 쿨링감',
    flavor: '쿨민트',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: false,
  },
  // ID: 8
  {
    id: '8',
    name: '코스모스 체리콜라',
    brand: '코스모스',
    price: 8500,
    rating: 4.4,
    reviewCount: 76,
    image: '/images/cosmos-cherrycola.jpg',
    images: [
      '/images/cosmos-cherrycola.jpg',
      '/images/cosmos-cherrycola-2.jpg',
    ],
    description: '달콤한 체리와 톡 쏘는 콜라의 만남',
    flavor: '체리콜라',
    nicotine: '6mg',
    volume: '30ml',
    inStock: false,
    isPopular: false,
    isNew: true,
  },
  // ID: 9
  {
    id: '9',
    name: '맥스웰 초콜릿쿠키',
    brand: '맥스웰',
    price: 15500,
    originalPrice: 18000,
    discount: 14,
    rating: 4.8,
    reviewCount: 198,
    image: '/images/maxwell-chocochip.jpg',
    images: [
      '/images/maxwell-chocochip.jpg',
      '/images/maxwell-chocochip-2.jpg',
      '/images/maxwell-chocochip-3.jpg',
    ],
    description: '진짜 초콜릿칩 쿠키를 먹는 듯한 달콤함',
    flavor: '초콜릿쿠키',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  // ID: 10
  {
    id: '10',
    name: '더원 피치아이스티',
    brand: '더원',
    price: 11000,
    rating: 4.2,
    reviewCount: 88,
    image: '/images/theone-peachicetea.jpg',
    images: ['/images/theone-peachicetea.jpg'],
    description: '달콤한 복숭아와 시원한 아이스티의 조화',
    flavor: '피치아이스티',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  // ID: 11
  {
    id: '11',
    name: '나스티 블루베리머핀',
    brand: '나스티',
    price: 13000,
    originalPrice: 15500,
    discount: 16,
    rating: 4.7,
    reviewCount: 142,
    image: '/images/nasty-blueberrymuffin.jpg',
    images: [
      '/images/nasty-blueberrymuffin.jpg',
      '/images/nasty-blueberrymuffin-2.jpg',
    ],
    description: '갓 구운 블루베리 머핀의 따뜻한 맛',
    flavor: '블루베리머핀',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  // ID: 12
  {
    id: '12',
    name: '프리미엄 오렌지크림',
    brand: '프리미엄',
    price: 16000,
    originalPrice: 19000,
    discount: 16,
    rating: 4.5,
    reviewCount: 67,
    image: '/images/premium-orangecream.jpg',
    images: ['/images/premium-orangecream.jpg'],
    description: '상큼한 오렌지와 부드러운 크림의 환상적 조화',
    flavor: '오렌지크림',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  // ID: 13
  {
    id: '13',
    name: '코스모스 망고라시',
    brand: '코스모스',
    price: 9000,
    rating: 4.3,
    reviewCount: 95,
    image: '/images/cosmos-mangolassi.jpg',
    images: [
      '/images/cosmos-mangolassi.jpg',
      '/images/cosmos-mangolassi-2.jpg',
    ],
    description: '인도 전통 망고라시의 진짜 맛',
    flavor: '망고라시',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: false,
  },
  // ID: 14
  {
    id: '14',
    name: '맥스웰 카라멜마키아토',
    brand: '맥스웰',
    price: 14000,
    originalPrice: 16500,
    discount: 15,
    rating: 4.6,
    reviewCount: 156,
    image: '/images/maxwell-caramelmacchiato.jpg',
    images: ['/images/maxwell-caramelmacchiato.jpg'],
    description: '달콤한 카라멜과 진한 커피의 완벽한 밸런스',
    flavor: '카라멜마키아토',
    nicotine: '6mg',
    volume: '30ml',
    inStock: false,
    isPopular: true,
    isNew: false,
  },
  // ID: 15
  {
    id: '15',
    name: '더원 수박소다',
    brand: '더원',
    price: 10000,
    rating: 4.1,
    reviewCount: 73,
    image: '/images/theone-watermelonsoda.jpg',
    images: [
      '/images/theone-watermelonsoda.jpg',
      '/images/theone-watermelonsoda-2.jpg',
    ],
    description: '여름 수박의 시원함과 톡 쏘는 소다',
    flavor: '수박소다',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  // ID: 16
  {
    id: '16',
    name: '나스티 딸기케이크',
    brand: '나스티',
    price: 12500,
    originalPrice: 14000,
    discount: 11,
    rating: 4.7,
    reviewCount: 189,
    image: '/images/nasty-strawberrycake.jpg',
    images: ['/images/nasty-strawberrycake.jpg'],
    description: '달콤한 딸기와 부드러운 케이크의 환상적 만남',
    flavor: '딸기케이크',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  // ID: 17
  {
    id: '17',
    name: '프리미엄 라벤더허니',
    brand: '프리미엄',
    price: 17500,
    originalPrice: 20000,
    discount: 13,
    rating: 4.4,
    reviewCount: 52,
    image: '/images/premium-lavenderhoney.jpg',
    images: ['/images/premium-lavenderhoney.jpg'],
    description: '은은한 라벤더와 달콤한 꿀의 고급스러운 향',
    flavor: '라벤더허니',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  // ID: 18
  {
    id: '18',
    name: '코스모스 청포도에이드',
    brand: '코스모스',
    price: 8800,
    rating: 4.2,
    reviewCount: 84,
    image: '/images/cosmos-grapeade.jpg',
    images: ['/images/cosmos-grapeade.jpg'],
    description: '상큼한 청포도와 시원한 에이드의 완벽 조화',
    flavor: '청포도에이드',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: false,
  },
  // ID: 19
  {
    id: '19',
    name: '맥스웰 티라미수',
    brand: '맥스웰',
    price: 16500,
    originalPrice: 19000,
    discount: 13,
    rating: 4.8,
    reviewCount: 203,
    image: '/images/maxwell-tiramisu.jpg',
    images: ['/images/maxwell-tiramisu.jpg', '/images/maxwell-tiramisu-2.jpg'],
    description: '이탈리아 정통 티라미수의 진짜 맛',
    flavor: '티라미수',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  // ID: 20
  {
    id: '20',
    name: '더원 키위드래곤',
    brand: '더원',
    price: 11500,
    rating: 4.3,
    reviewCount: 96,
    image: '/images/theone-kiwidragon.jpg',
    images: ['/images/theone-kiwidragon.jpg'],
    description: '이색적인 키위와 드래곤프루트의 열대 조합',
    flavor: '키위드래곤',
    nicotine: '3mg',
    volume: '60ml',
    inStock: false,
    isPopular: false,
    isNew: true,
  },
];

const MOCK_USER_PROFILES: UserProfile[] = [
  {
    id: '1',
    name: '김민준',
    email: 'test@juicepick.com',
    phone: '010-1234-5678',
    birthDate: '1990-05-15',
    gender: 'male',
    address: {
      zipCode: '06142',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
    },
    preferences: {
      newsletter: true,
      smsMarketing: false,
      pushNotifications: true,
    },
  },
  {
    id: '2',
    name: '관리자',
    email: 'admin@juicepick.com',
    phone: '010-9876-5432',
    birthDate: '1985-03-20',
    gender: 'male',
    address: {
      zipCode: '04512',
      address: '서울특별시 중구 세종대로 110',
      detailAddress: '관리자실',
    },
    preferences: {
      newsletter: true,
      smsMarketing: true,
      pushNotifications: true,
    },
  },
  {
    id: '3',
    name: '일반 사용자',
    email: 'user@example.com',
    phone: '010-5555-6666',
    birthDate: '1995-12-10',
    gender: 'female',
    address: {
      zipCode: '07654',
      address: '경기도 성남시 분당구 판교역로 166',
      detailAddress: '101동 2002호',
    },
    preferences: {
      newsletter: false,
      smsMarketing: false,
      pushNotifications: false,
    },
  },
];

const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'test@juicepick.com',
    password: '123456',
    name: '테스트 유저',
    role: 'user',
  },
  {
    id: '2',
    email: 'admin@juicepick.com',
    password: 'admin123',
    name: '관리자',
    role: 'admin',
  },
  {
    id: '3',
    email: 'user@example.com',
    password: 'password',
    name: '일반 사용자',
    role: 'user',
  },
];

const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 1,
    title: '나스티 쿠션맨 맛 후기 - 완전 대박!',
    content:
      '드디어 나스티 쿠션맨 액상을 써봤는데 정말 맛이 좋네요. 과일 맛이 진짜 진하고 목넘김도 부드러워서 계속 빨게 되더라고요. 니코틴 3mg로 했는데 딱 적당한 것 같아요.',
    author: '베이프러버',
    category: '제품후기',
    likes: 42,
    views: 1234,
    comments: 18,
    createdAt: '2시간 전',
    isPinned: true,
    isHot: true,
  },
  {
    id: 2,
    title: '액상 DIY 레시피 공유합니다',
    content:
      '오랫동안 연구한 DIY 레시피를 공유해요. PG/VG 비율은 30/70으로 하고 니코틴은 6mg으로 맞춰봤는데 정말 만족스러운 결과가 나왔어요. 재료와 비율을 자세히 알려드릴게요.',
    author: 'DIY마스터',
    category: 'DIY/팁',
    likes: 28,
    views: 856,
    comments: 12,
    createdAt: '4시간 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 3,
    title: '초보자 질문 - 니코틴 함량 추천 부탁드려요',
    content:
      '담배를 끊으려고 전자담배를 시작하려는데 니코틴 함량을 얼마나 해야할지 모르겠어요. 하루에 한 갑 정도 피웠는데 몇 mg로 시작하는게 좋을까요? 경험자분들 조언 부탁드립니다.',
    author: '금연도전자',
    category: '질문/답변',
    likes: 15,
    views: 623,
    comments: 25,
    createdAt: '6시간 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 4,
    title: '온라인 쇼핑몰별 가격 비교해봤어요',
    content:
      '주요 온라인몰에서 같은 제품 가격을 비교해봤는데 차이가 꽤 나네요. 쿠폰이나 적립금까지 고려하면 더 차이가 벌어져요. 정리한 내용 공유드릴게요.',
    author: '가격헌터',
    category: '정보공유',
    likes: 67,
    views: 2341,
    comments: 8,
    createdAt: '8시간 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 5,
    title: '맥스웰 신제품 출시 소식!',
    content:
      '맥스웰에서 새로운 맛 출시한다고 하네요. 망고 키위 믹스라고 하는데 언제부터 판매하는지 아시는 분 계신가요? 벌써 기대되네요.',
    author: '뉴스헌터',
    category: '뉴스/소식',
    likes: 23,
    views: 789,
    comments: 14,
    createdAt: '12시간 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 6,
    title: '코일 수명 늘리는 꿀팁 공유',
    content:
      '코일을 오래 쓸 수 있는 방법들을 정리해봤습니다. 프라이밍 방법부터 사용 중 주의사항까지 상세히 설명드릴게요. 도움이 되시길 바랍니다.',
    author: '베테랑유저',
    category: 'DIY/팁',
    likes: 31,
    views: 1456,
    comments: 6,
    createdAt: '1일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 7,
    title: '전자담배 시작한 지 6개월 후기',
    content:
      '금연을 위해 전자담배를 시작한 지 6개월이 되었네요. 처음엔 어색했는데 이제는 완전히 적응했고 담배 생각도 안 나요. 과정과 팁을 공유해드릴게요.',
    author: '금연성공자',
    category: '제품후기',
    likes: 89,
    views: 3421,
    comments: 31,
    createdAt: '2일 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 8,
    title: '액상 보관 방법 질문이요',
    content:
      '액상을 어떻게 보관해야 오래 쓸 수 있나요? 냉장고에 넣어도 되는지, 직사광선만 피하면 되는지 궁금해요.',
    author: '보관고민',
    category: '질문/답변',
    likes: 12,
    views: 445,
    comments: 8,
    createdAt: '3일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 9,
    title: '파스텔 신상 액상 맛 리뷰',
    content:
      '파스텔에서 나온 신상 스트로베리 크림 맛을 써봤는데 정말 달콤하고 부드러워요. 디저트 계열 좋아하시는 분들께 강추드립니다. VG 비율이 높아서 연기도 풍성해요.',
    author: '달콤이',
    category: '제품후기',
    likes: 35,
    views: 921,
    comments: 16,
    createdAt: '4일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 10,
    title: '전자담배 입문자를 위한 기기 추천',
    content:
      '전자담배를 처음 시작하는 분들을 위해 입문용 기기들을 정리해봤어요. 가격대별로 나누어서 추천드리니 참고하세요. 각각의 장단점도 함께 설명드릴게요.',
    author: '초보도우미',
    category: '정보공유',
    likes: 76,
    views: 2187,
    comments: 22,
    createdAt: '5일 전',
    isPinned: true,
    isHot: true,
  },
  {
    id: 11,
    title: 'RDA vs RTA 어떤 게 좋을까요?',
    content:
      'DIY를 시작하려고 하는데 RDA와 RTA 중 어떤 걸 선택해야 할지 고민이에요. 각각의 특징과 차이점을 알려주시면 감사하겠습니다.',
    author: 'DIY입문생',
    category: '질문/답변',
    likes: 18,
    views: 534,
    comments: 11,
    createdAt: '6일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 12,
    title: '월드컵 액상 한정판 출시!',
    content:
      '월드컵 기념으로 특별 한정판 액상이 출시됐네요. 패키징도 예쁘고 맛도 독특해서 컬렉션으로도 좋을 것 같아요. 벌써 품절되는 곳도 있더라고요.',
    author: '한정판수집가',
    category: '뉴스/소식',
    likes: 44,
    views: 1123,
    comments: 7,
    createdAt: '1주일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 13,
    title: '배터리 안전 관리 팁',
    content:
      '배터리 관리를 잘못하면 위험할 수 있어요. 충전 방법, 보관 방법, 교체 시기 등 안전하게 사용하는 방법들을 정리해봤습니다. 꼭 읽어보시고 안전하게 사용하세요.',
    author: '안전제일',
    category: 'DIY/팁',
    likes: 92,
    views: 2876,
    comments: 15,
    createdAt: '1주일 전',
    isPinned: true,
    isHot: true,
  },
  {
    id: 14,
    title: '오프라인 매장 추천해주세요',
    content:
      '서울 강남 쪽에서 좋은 전자담배 매장 찾고 있어요. 제품 종류도 많고 친절한 곳으로 추천 부탁드립니다. 가격도 합리적이면 더 좋겠어요.',
    author: '매장탐방가',
    category: '질문/답변',
    likes: 26,
    views: 687,
    comments: 19,
    createdAt: '1주일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 15,
    title: '여름철 액상 관리 주의사항',
    content:
      '날씨가 더워지면서 액상 관리에 더 신경써야 할 것 같아요. 고온에서 변질될 수 있으니 보관 장소와 온도에 주의하시기 바랍니다. 차 안에 두지 마세요!',
    author: '여름준비',
    category: 'DIY/팁',
    likes: 39,
    views: 1234,
    comments: 9,
    createdAt: '2주일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 16,
    title: '크레이지 액상 신맛 리뷰',
    content:
      '크레이지에서 나온 블루베리 레몬 맛을 써봤는데 상큼함이 정말 좋네요. 여름에 딱 맞는 맛인 것 같아요. 시원하고 개운한 느낌이 일품입니다.',
    author: '상큼러버',
    category: '제품후기',
    likes: 31,
    views: 876,
    comments: 13,
    createdAt: '2주일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 17,
    title: '해외 직구 vs 국내 구매 비교',
    content:
      '해외 직구와 국내 구매의 장단점을 비교 분석해봤어요. 가격, 배송, AS, 세금 등 여러 요소를 고려해서 정리했습니다. 구매 전에 참고하세요.',
    author: '직구전문가',
    category: '정보공유',
    likes: 58,
    views: 1987,
    comments: 24,
    createdAt: '2주일 전',
    isPinned: false,
    isHot: true,
  },
  {
    id: 18,
    title: '니코틴 솔트 vs 프리베이스 차이점',
    content:
      '니코틴 솔트와 프리베이스의 차이가 뭔지 궁금해요. 어떤 상황에서 어떤 걸 쓰는 게 좋은지 경험담 공유해주시면 감사하겠습니다.',
    author: '궁금이',
    category: '질문/답변',
    likes: 22,
    views: 665,
    comments: 17,
    createdAt: '3주일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 19,
    title: '클리어로마이저 청소 방법',
    content:
      '클리어로마이저를 깨끗하게 청소하는 방법을 알려드릴게요. 단계별로 자세히 설명하니 따라해보세요. 정기적인 청소로 더 오래 사용할 수 있어요.',
    author: '청소마스터',
    category: 'DIY/팁',
    likes: 47,
    views: 1543,
    comments: 8,
    createdAt: '3주일 전',
    isPinned: false,
    isHot: false,
  },
  {
    id: 20,
    title: '전자담배 법규 변경 소식',
    content:
      '전자담배 관련 법규가 일부 변경된다고 하네요. 사용자들이 알아야 할 주요 변경사항들을 정리해서 공유드립니다. 미리 확인해두시기 바랍니다.',
    author: '법규알리미',
    category: '뉴스/소식',
    likes: 83,
    views: 2654,
    comments: 28,
    createdAt: '3주일 전',
    isPinned: false,
    isHot: true,
  },
];

const MOCK_COMMUNITY_CATEGORIES: CommunityCategory[] = [
  { name: '전체', count: 1247, color: 'bg-blue-50 text-blue-700' },
  { name: '제품후기', count: 456, color: 'bg-green-50 text-green-700' },
  { name: '질문/답변', count: 321, color: 'bg-orange-50 text-orange-700' },
  { name: 'DIY/팁', count: 234, color: 'bg-purple-50 text-purple-700' },
  { name: '정보공유', count: 156, color: 'bg-red-50 text-red-700' },
  { name: '뉴스/소식', count: 80, color: 'bg-indigo-50 text-indigo-700' },
];

const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    productName: '나스티 쿠션맨 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '정말 맛있는 액상입니다!',
    content:
      '처음에는 기대 안했는데 정말 맛있어요. 과일 맛이 진하고 목넘김도 부드러워서 매일 사용하고 있습니다. 특히 아침에 커피 대신 이걸로 시작하면 기분이 좋아져요.',
    author: '베이프러버123',
    date: '2024-01-15',
    helpful: 42,
    notHelpful: 3,
    comments: 8,
    verified: true,
    pros: ['진한 과일맛', '부드러운 목넘김', '가성비 좋음'],
    cons: ['냄새가 좀 강함'],
    tags: ['과일맛', '입문자추천', '가성비'],
  },
  {
    id: 2,
    productName: '코스모스 블루베리 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '블루베리 맛이 진짜네요',
    content:
      '블루베리 액상을 많이 써봤는데 이게 제일 진짜 블루베리 같아요. 달콤함도 적당하고 연무량도 만족스럽습니다. 다만 가격이 조금 비싼게 아쉬워요.',
    author: '과일맛헌터',
    date: '2024-01-14',
    helpful: 28,
    notHelpful: 2,
    comments: 5,
    verified: true,
    pros: ['진짜 블루베리맛', '적당한 단맛', '좋은 연무량'],
    cons: ['가격이 비쌈', '용량이 아쉬움'],
    tags: ['블루베리', '진짜맛', '연무량'],
  },
  {
    id: 3,
    productName: '맥스웰 민트 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '민트맛은 좋은데...',
    content:
      '민트 향이 정말 시원하고 좋아요. 여름에 쓰기 딱 좋을 것 같습니다. 하지만 코일 수명이 짧아지는 느낌이에요. 그래도 민트 좋아하시면 추천드려요.',
    author: '민트매니아',
    date: '2024-01-13',
    helpful: 19,
    notHelpful: 1,
    comments: 12,
    verified: false,
    pros: ['시원한 민트', '여름용으로 좋음'],
    cons: ['코일 수명 단축', '목이 아플 때 있음'],
    tags: ['민트', '시원함', '여름용'],
  },
  {
    id: 4,
    productName: '더원 망고 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '망고 맛 진짜 끝내줍니다',
    content:
      '망고 액상 중에서 최고인 것 같아요. 향도 좋고 맛도 진짜 망고 같아요. 니코틴도 적당해서 하루 종일 써도 목이 아프지 않아요. 강력 추천!',
    author: '망고사랑',
    date: '2024-01-12',
    helpful: 35,
    notHelpful: 0,
    comments: 6,
    verified: true,
    pros: ['진짜 망고맛', '좋은 향', '적당한 니코틴'],
    cons: [],
    tags: ['망고', '향좋음', '니코틴적당'],
  },
  {
    id: 5,
    productName: '베이프윌 딸기 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '딸기 맛 괜찮아요',
    content:
      '달달한 딸기 맛이 좋네요. 인공적인 맛이 아니라 자연스러운 딸기 맛입니다. 가격도 저렴해서 부담 없이 쓸 수 있어요.',
    author: '딸기좋아',
    date: '2024-01-11',
    helpful: 22,
    notHelpful: 4,
    comments: 3,
    verified: true,
    pros: ['자연스러운 딸기맛', '저렴한 가격', '달달함'],
    cons: ['연무량이 적음'],
    tags: ['딸기', '저렴', '달콤'],
  },
  {
    id: 6,
    productName: '나스티 그린애플 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '상큼한 그린애플!',
    content:
      '정말 상큼한 그린애플 맛이에요. 새콤달콤해서 질리지 않고 계속 빨게 되네요. 특히 더운 날씨에 시원하게 즐기기 좋아요.',
    author: '애플러버',
    date: '2024-01-10',
    helpful: 31,
    notHelpful: 2,
    comments: 9,
    verified: true,
    pros: ['상큼한 맛', '질리지 않음', '시원함'],
    cons: ['조금 시큼함'],
    tags: ['사과', '상큼', '시원함'],
  },
  {
    id: 7,
    productName: '코스모스 스트로베리 밀크',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '딸기우유 그 자체!',
    content:
      '진짜 딸기우유 마시는 느낌이에요. 달콤하고 부드러워서 스트레스 받을 때 피우면 기분이 좋아져요. 연무량도 많고 만족스럽습니다.',
    author: '스트로베리킹',
    date: '2024-01-09',
    helpful: 45,
    notHelpful: 1,
    comments: 11,
    verified: true,
    pros: ['진짜 딸기우유맛', '달콤함', '좋은 연무량'],
    cons: ['칼로리 걱정됨'],
    tags: ['딸기', '우유', '달콤', '연무량'],
  },
  {
    id: 8,
    productName: '더원 바닐라 크림',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '바닐라 맛은 좋지만...',
    content:
      '바닐라 크림 맛은 정말 좋아요. 부드럽고 달콤해서 디저트 같은 느낌입니다. 하지만 너무 달아서 금방 질려요. 가끔씩 즐기기에는 좋을 것 같아요.',
    author: '바닐라매니아',
    date: '2024-01-08',
    helpful: 18,
    notHelpful: 5,
    comments: 4,
    verified: false,
    pros: ['부드러운 바닐라', '디저트 같은 맛'],
    cons: ['너무 달음', '쉽게 질림'],
    tags: ['바닐라', '디저트', '달콤'],
  },
  {
    id: 9,
    productName: '파스텔 레몬 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '새콤달콤 레몬의 정석',
    content:
      '레몬 맛이 정말 상큼해요. 새콤함이 적당해서 입안이 개운해지는 느낌입니다. 여름철에 더위 날릴 때 딱 좋을 것 같아요. 다만 향이 너무 강해서 주변 사람들이 알아채요.',
    author: '레몬사랑',
    date: '2024-01-07',
    helpful: 24,
    notHelpful: 3,
    comments: 7,
    verified: true,
    pros: ['상큼한 레몬맛', '개운함', '여름철 최적'],
    cons: ['향이 너무 강함', '새콤함이 강할 때 있음'],
    tags: ['레몬', '상큼', '여름용'],
  },
  {
    id: 10,
    productName: '크레이지 포도 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '포도 액상의 끝판왕',
    content:
      '포도 액상을 정말 많이 써봤는데 이게 최고예요. 진짜 포도주스 마시는 느낌이고 달콤함도 완벽해요. 목넘김도 부드럽고 연무량도 풍성합니다. 재구매 확정!',
    author: '포도왕자',
    date: '2024-01-06',
    helpful: 52,
    notHelpful: 1,
    comments: 15,
    verified: true,
    pros: ['진짜 포도맛', '완벽한 달콤함', '부드러운 목넘김', '풍성한 연무량'],
    cons: [],
    tags: ['포도', '달콤', '연무량', '재구매'],
  },
  {
    id: 11,
    productName: '월드컵 키위 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '키위 맛은 독특해요',
    content:
      '키위 액상은 처음 써보는데 생각보다 독특하네요. 새콤달콤한 맛이 나는데 호불호가 갈릴 것 같아요. 저는 개인적으로 괜찮았지만 만족스럽지는 않았어요.',
    author: '키위도전자',
    date: '2024-01-05',
    helpful: 16,
    notHelpful: 8,
    comments: 6,
    verified: false,
    pros: ['독특한 키위맛', '새콤달콤함'],
    cons: ['호불호 갈림', '만족도 보통'],
    tags: ['키위', '독특', '호불호'],
  },
  {
    id: 12,
    productName: '베이프윌 체리 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '달콤한 체리 맛 좋아요',
    content:
      '체리 맛이 달콤하고 향도 좋아요. 인공적이지 않고 자연스러운 체리 맛이 나서 마음에 들어요. 가격도 합리적이고 용량도 적당해서 부담 없이 즐길 수 있습니다.',
    author: '체리러버',
    date: '2024-01-04',
    helpful: 29,
    notHelpful: 2,
    comments: 8,
    verified: true,
    pros: ['자연스러운 체리맛', '좋은 향', '합리적 가격'],
    cons: ['약간 단조로움'],
    tags: ['체리', '달콤', '가성비'],
  },
  {
    id: 13,
    productName: '맥스웰 오렌지 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '상큼한 오렌지의 매력',
    content:
      '오렌지 맛이 정말 상큼하고 시원해요. 아침에 피우면 잠이 확 깨는 느낌입니다. 비타민을 먹는 기분이에요. 연무량도 적당하고 목넘김도 부드러워요.',
    author: '오렌지팬',
    date: '2024-01-03',
    helpful: 33,
    notHelpful: 4,
    comments: 10,
    verified: true,
    pros: ['상큼한 오렌지맛', '상쾌함', '부드러운 목넘김'],
    cons: ['향이 금방 날아감'],
    tags: ['오렌지', '상큼', '상쾌함'],
  },
  {
    id: 14,
    productName: '나스티 메론 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '메론 맛의 새로운 경험',
    content:
      '메론 액상을 처음 써보는데 정말 신세계예요. 달콤하고 부드러운 메론 맛이 입안에 가득해요. 고급스러운 느낌이 들고 연무량도 많아서 만족스럽습니다.',
    author: '메론마니아',
    date: '2024-01-02',
    helpful: 38,
    notHelpful: 1,
    comments: 12,
    verified: true,
    pros: ['고급스러운 메론맛', '달콤함', '많은 연무량'],
    cons: ['가격이 약간 비쌈'],
    tags: ['메론', '고급', '연무량'],
  },
  {
    id: 15,
    productName: '코스모스 복숭아 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '복숭아의 달콤함',
    content:
      '복숭아 맛이 달콤하고 부드러워요. 여름 복숭아를 먹는 느낌이 들어서 기분이 좋아져요. 향도 은은하고 좋습니다. 다만 조금 더 진했으면 좋겠어요.',
    author: '복숭아공주',
    date: '2024-01-01',
    helpful: 26,
    notHelpful: 3,
    comments: 5,
    verified: true,
    pros: ['달콤한 복숭아맛', '은은한 향', '부드러움'],
    cons: ['맛이 조금 약함'],
    tags: ['복숭아', '달콤', '은은함'],
  },
  {
    id: 16,
    productName: '더원 콜라 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '콜라 맛? 독특하네요',
    content:
      '콜라 액상이라는게 신기해서 써봤는데 정말 콜라 맛이 나요. 탄산은 없지만 콜라의 그 특유한 맛이 느껴져요. 재미있지만 자주 쓰기에는 좀 그래요.',
    author: '콜라실험가',
    date: '2023-12-31',
    helpful: 21,
    notHelpful: 7,
    comments: 9,
    verified: false,
    pros: ['독특한 콜라맛', '재미있음'],
    cons: ['자주 쓰기 어려움', '호불호 갈림'],
    tags: ['콜라', '독특', '재미'],
  },
  {
    id: 17,
    productName: '파스텔 요거트 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '요거트 액상의 신세계',
    content:
      '요거트 액상이라니 정말 신기했는데 맛이 환상적이에요. 새콤달콤하고 크리미한 맛이 정말 요거트 같아요. 디저트 액상으로는 최고인 것 같습니다.',
    author: '요거트킹',
    date: '2023-12-30',
    helpful: 44,
    notHelpful: 2,
    comments: 13,
    verified: true,
    pros: ['진짜 요거트맛', '크리미함', '새콤달콤함'],
    cons: ['조금 끈적한 느낌'],
    tags: ['요거트', '디저트', '크리미'],
  },
  {
    id: 18,
    productName: '월드컵 쿠키앤크림 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 4,
    title: '쿠키앤크림 맛 좋아요',
    content:
      '쿠키앤크림 맛이 정말 달콤하고 맛있어요. 오레오 과자 먹는 느낌이 들어서 기분이 좋아져요. 디저트 대신으로 딱 좋은 것 같습니다. 다만 너무 달아서 금방 질려요.',
    author: '쿠키몬스터',
    date: '2023-12-29',
    helpful: 27,
    notHelpful: 4,
    comments: 6,
    verified: true,
    pros: ['달콤한 쿠키맛', '오레오 느낌', '디저트 대용'],
    cons: ['너무 달아서 질림'],
    tags: ['쿠키', '디저트', '달콤'],
  },
  {
    id: 19,
    productName: '크레이지 아이스크림 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 5,
    title: '아이스크림 그 자체!',
    content:
      '정말 아이스크림 먹는 느낌이에요. 차가운 느낌은 없지만 크리미하고 달콤한 맛이 완벽해요. 여러 맛이 섞인 느낌이라 복잡하지만 조화롭습니다. 강력 추천!',
    author: '아이스크림러버',
    date: '2023-12-28',
    helpful: 41,
    notHelpful: 1,
    comments: 11,
    verified: true,
    pros: ['진짜 아이스크림맛', '크리미함', '복합적인 맛'],
    cons: ['가격이 비쌈'],
    tags: ['아이스크림', '크리미', '디저트'],
  },
  {
    id: 20,
    productName: '베이프윌 커피 액상',
    productImage: '/placeholder.svg?height=80&width=80',
    rating: 3,
    title: '커피 맛은 있지만...',
    content:
      '커피 액상이라고 해서 기대했는데 생각보다 밋밋해요. 커피 맛은 나지만 진한 맛을 기대하면 실망할 수 있어요. 아메리카노보다는 카페라떼 느낌이에요.',
    author: '커피중독자',
    date: '2023-12-27',
    helpful: 19,
    notHelpful: 6,
    comments: 8,
    verified: false,
    pros: ['커피 맛', '부드러움'],
    cons: ['밋밋함', '진한 맛 부족'],
    tags: ['커피', '라떼', '밋밋'],
  },
];

const MOCK_TOP_REVIEWERS: TopReviewer[] = [
  { name: '베이프러버123', reviews: 156, helpful: 2341 },
  { name: '과일맛헌터', reviews: 89, helpful: 1567 },
  { name: '리뷰왕', reviews: 134, helpful: 1432 },
  { name: '액상마스터', reviews: 67, helpful: 987 },
];

const FILTER_TAGS = [
  '전체',
  '과일맛',
  '민트',
  '담배맛',
  '디저트',
  '입문자추천',
  '가성비',
  '프리미엄',
  '고농도',
  '저농도',
];

export {
  MOCK_ORDERS,
  MOCK_PRODUCTS,
  MOCK_USER_PROFILES,
  MOCK_USERS,
  MOCK_COMMUNITY_POSTS,
  MOCK_COMMUNITY_CATEGORIES,
  MOCK_REVIEWS,
  MOCK_TOP_REVIEWERS,
  FILTER_TAGS,
};
