import { Order } from '@/types/order';
import { Product } from '@/types/product';
import { UserProfile } from '@/types/profile';
import { User } from '@/types/user';

const MOCK_ORDERS: Order[] = [
  {
    id: 'ORDER-001',
    userId: '1',
    items: [
      {
        id: 'cart-1',
        productId: '1',
        name: '나스티 망고 아이스',
        brand: '나스티',
        price: 12000,
        image: '/images/nasty-mango.jpg',
        quantity: 2,
      },
      {
        id: 'cart-2',
        productId: '3',
        name: '맥스웰 블루베리 타르트',
        brand: '맥스웰',
        price: 13500,
        image: '/images/maxwell-blueberry.jpg',
        quantity: 1,
      },
    ],
    totalAmount: 37500,
    status: 'delivered',
    orderDate: '2024-08-15',
    deliveryDate: '2024-08-18',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
  {
    id: 'ORDER-002',
    userId: '1',
    items: [
      {
        id: 'cart-3',
        productId: '2',
        name: '코스모스 스트로베리 밀크',
        brand: '코스모스',
        price: 8000,
        image: '/images/cosmos-strawberry.jpg',
        quantity: 3,
      },
    ],
    totalAmount: 24000,
    status: 'shipped',
    orderDate: '2024-08-28',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
  {
    id: 'ORDER-003',
    userId: '1',
    items: [
      {
        id: 'cart-4',
        productId: '5',
        name: '나스티 그린애플',
        brand: '나스티',
        price: 11000,
        image: '/images/nasty-greenapple.jpg',
        quantity: 1,
      },
    ],
    totalAmount: 11000,
    status: 'processing',
    orderDate: '2024-09-01',
    shippingAddress: {
      name: '김민준',
      phone: '010-1234-5678',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
      zipCode: '06142',
    },
  },
];

const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: '나스티 망고 아이스',
    brand: '나스티',
    price: 12000,
    originalPrice: 15000,
    discount: 20,
    rating: 4.8,
    reviewCount: 124,
    image: '/images/nasty-mango.jpg',
    images: [
      '/images/nasty-mango.jpg',
      '/images/nasty-mango-2.jpg',
      '/images/nasty-mango-3.jpg',
    ],
    description:
      '망고의 달콤함과 시원한 아이스가 만나 완벽한 조화를 이루는 프리미엄 액상',
    flavor: '망고 아이스',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  {
    id: '2',
    name: '코스모스 스트로베리 밀크',
    brand: '코스모스',
    price: 8000,
    rating: 4.6,
    reviewCount: 89,
    image: '/images/cosmos-strawberry.jpg',
    images: [
      '/images/cosmos-strawberry.jpg',
      '/images/cosmos-strawberry-2.jpg',
    ],
    description: '신선한 딸기와 부드러운 우유의 완벽한 조화',
    flavor: '스트로베리 밀크',
    nicotine: '6mg',
    volume: '30ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
  {
    id: '3',
    name: '맥스웰 블루베리 타르트',
    brand: '맥스웰',
    price: 13500,
    originalPrice: 16000,
    discount: 15,
    rating: 4.7,
    reviewCount: 156,
    image: '/images/maxwell-blueberry.jpg',
    images: [
      '/images/maxwell-blueberry.jpg',
      '/images/maxwell-blueberry-2.jpg',
      '/images/maxwell-blueberry-3.jpg',
    ],
    description: '진짜 블루베리 타르트를 먹는 듯한 달콤하고 새콤한 맛',
    flavor: '블루베리 타르트',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: true,
    isNew: false,
  },
  {
    id: '4',
    name: '더원 바닐라 크림',
    brand: '더원',
    price: 9500,
    rating: 4.4,
    reviewCount: 67,
    image: '/images/theone-vanilla.jpg',
    images: ['/images/theone-vanilla.jpg', '/images/theone-vanilla-2.jpg'],
    description: '부드럽고 진한 바닐라 크림의 깊은 맛',
    flavor: '바닐라 크림',
    nicotine: '6mg',
    volume: '30ml',
    inStock: false,
    isPopular: false,
    isNew: false,
  },
  {
    id: '5',
    name: '나스티 그린애플',
    brand: '나스티',
    price: 11000,
    rating: 4.5,
    reviewCount: 78,
    image: '/images/nasty-greenapple.jpg',
    images: ['/images/nasty-greenapple.jpg'],
    description: '상큼한 그린애플의 깔끔하고 시원한 맛',
    flavor: '그린애플',
    nicotine: '3mg',
    volume: '60ml',
    inStock: true,
    isPopular: false,
    isNew: true,
  },
];

const MOCK_USER_PROFILES: UserProfile[] = [
  {
    id: '1',
    name: '김민준',
    email: 'test@juicepick.com',
    phone: '010-1234-5678',
    birthDate: '1990-05-15',
    gender: 'male',
    address: {
      zipCode: '06142',
      address: '서울특별시 강남구 테헤란로 123',
      detailAddress: '456호',
    },
    preferences: {
      newsletter: true,
      smsMarketing: false,
      pushNotifications: true,
    },
  },
  {
    id: '2',
    name: '관리자',
    email: 'admin@juicepick.com',
    phone: '010-9876-5432',
    birthDate: '1985-03-20',
    gender: 'male',
    address: {
      zipCode: '04512',
      address: '서울특별시 중구 세종대로 110',
      detailAddress: '관리자실',
    },
    preferences: {
      newsletter: true,
      smsMarketing: true,
      pushNotifications: true,
    },
  },
  {
    id: '3',
    name: '일반 사용자',
    email: 'user@example.com',
    phone: '010-5555-6666',
    birthDate: '1995-12-10',
    gender: 'female',
    address: {
      zipCode: '07654',
      address: '경기도 성남시 분당구 판교역로 166',
      detailAddress: '101동 2002호',
    },
    preferences: {
      newsletter: false,
      smsMarketing: false,
      pushNotifications: false,
    },
  },
];

const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'test@juicepick.com',
    password: '123456',
    name: '테스트 유저',
    role: 'user',
  },
  {
    id: '2',
    email: 'admin@juicepick.com',
    password: 'admin123',
    name: '관리자',
    role: 'admin',
  },
  {
    id: '3',
    email: 'user@example.com',
    password: 'password',
    name: '일반 사용자',
    role: 'user',
  },
];

export { MOCK_ORDERS, MOCK_PRODUCTS, MOCK_USER_PROFILES, MOCK_USERS };
